frontend_base_url: http://127.0.0.1:4201
allow_origins: []

return_reservation_reminder_cron_time: 10:00:00
reservation_code_length: 6
reservation_code_chars: "123456789"
reservation_automatic_return: True

device_api_key: 'abcdefg'

mongo:
  uri: mongodb://127.0.0.1:27017/depot

oauth2:
  server_metadata_url: 'http://127.0.0.1:8000/.well-known/openid-configuration'
  client_id: 'depot'
  client_secret: 'i0CQLpy95zp4yj1UgdzJCTvFkXLK0ZwI'

mail:
  host: localhost
  sender: "admin@localhost"
  #port: 25
  #ssl: false
  #starttls: false
  #keyfile: null
  #certfile: null
  #user: ""
  #password: ""
